# vi: ft=yaml.ansible
---
- name: Apt dependencies
  ansible.builtin.apt:
    name:
      - gcc
      - clang
      - git
      - nodejs
      - npm
      - ripgrep
      - fd-find
      - fzf
      - python3
      - python3-pip
      - python3-venv
      - lua5.4
      - luarocks

# - name: NPM dependencies
#   community.general.npm:
#     name: tree-sitter-cli
#     global: true

- name: Cargo dependencies
  become: false
  community.general.cargo:
    name: tree-sitter-cli
    state: present

- name: Install NEOVIM
  community.general.snap:
    name: nvim
    state: present
    classic: true

- name: Create Link to NVIM binary
  ansible.builtin.file:
    src: /snap/bin/nvim
    dest: /bin/nvim
    state: link
