# vi: ft=yaml.ansible
---
- name: Full => install dev tools
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - snapd
    - gnupg
    - software-properties-common
    - git
    - openssh-server
    - openssh-client
    - build-essential
    - jq
    - ripgrep
    - fd-find
    - fzf
    - ca-certificates


- name: Full => install proggramming languages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - python3
    - python3-pip
    - python3-venv
    - nodejs
    - npm
    - golang
    - default-jdk
    - php-cli
    - php-curl
    - lua5.4
    - luarocks


- name: Check if Rust is installed
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  register: rustc_binary


- name: Download rustup-init script
  become: true
  become_user: "{{ ansible_user }}"
  when: not rustc_binary.stat.exists
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init.sh
    mode: "0755"


- name: Install Rust non-interactively
  become: true
  become_user: "{{ ansible_user }}"
  when: not rustc_binary.stat.exists
  ansible.builtin.command:
    cmd: /tmp/rustup-init.sh -y
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"


- name: Ensure Docker apt keyring directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"


- name: Download Docker official GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: ansible_distribution == "Debian"


- name: Download Docker official GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: ansible_distribution == "ubuntu"


- name: Add Docker apt repository
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"
    content: >-
      deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/debian
      {{ ansible_distribution_release }} stable
  when: ansible_distribution == "Debian"


- name: Add Docker apt repository
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"
    content: >-
      deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
  when: ansible_distribution == "Ubuntu"


- name: Add Oracle VirtualBox GPG key
  ansible.builtin.apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present


- name: Add VirtualBox repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present


- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present


- name: Add HashiCorp official repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present


- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true


- name: Full => install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin


- name: Install VirtualBox
  ansible.builtin.apt:
    name: virtualbox-7.2
    state: present


- name: Install Hashicorp vagrant and terraform
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - vagrant
    - terraform


- name: Extra packages
  when: extra_packages is defined
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
    name: "{{ item }}"
  loop: "{{ extra_packages }}"

- name: Reset connection
  ansible.builtin.meta: reset_connection
