# vi: ft=yaml.ansible
---
- name: Minimal => install Drivers
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 86400
  loop:
    - bluez


- name: Minimal => install essential CLI and networking tools
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - zsh
    - curl
    - wget
    - acl
    - net-tools
    - zip
    - htop
    - tmux


- name: Try to install eza
  ansible.builtin.apt:
    name: eza
    state: present
  register: eza_install
  ignore_errors: true


- name: Install exa if eza is unavailable
  when: eza_install.failed
  ansible.builtin.apt:
    name: exa
    state: present
  register: exa_install
  ignore_errors: true


- name: Change Timezone
  when: timezone is defined
  community.general.timezone:
    name: "{{ timezone }}"


- name: Copy Terminfo
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dotfiles/shared/xterm-ghostty.src"
    dest: /tmp/xterm-ghostty.src
    mode: "0777"


- name: Compile Terminfo
  ansible.builtin.command:
    cmd: tic -x -o /usr/share/terminfo/ /tmp/xterm-ghostty.src
    creates: "/usr/share/terminfo/x/xterm-ghostty"
