# vi: ft=yaml.ansible
---
- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_binary


- name: Install Homebrew
  ansible.builtin.shell: |
    NONINTERACTIVE=1 /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  when:
    - not homebrew_binary.stat.exists


- name: Refresh shell environment
  ansible.builtin.command:
    cmd: /opt/homebrew/bin/brew --version
  changed_when: false

- name: Install Packages
  become: false
  community.general.homebrew:
    name: "{{ item }}"
    update_homebrew: true
    upgrade: true
  loop:
    - inetutils
    - tmux
    - htop
    - git
    - eza
    - wget
    - jq
    - tree
    - ripgrep
    - fd
    - fzf
    - python3
    - node
    - go
    - openjdk
    - php
    - lua
    - luarocks
    - tree-sitter-cli
    - rust
    - docker
    - docker-compose
    - docker-buildx
    - colima


- name: Start Colima
  become: false
  ansible.builtin.command:
    cmd: colima start
  register: colima_start
  changed_when: "'already running' not in colima_start.stdout"


- name: Install Extra Packages
  become: false
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ extra_packages }}"
  when: extra_packages is defined


- name: Change Timezone
  ansible.builtin.command:
    cmd: "systemsetup -settimezone '{{ timezone }}'"
  register: timezone_register
  changed_when: false
  check_mode: false


- name: Copy Terminfo
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dotfiles/shared/xterm-ghostty.src"
    dest: /tmp/xterm-ghostty.src
    mode: "0777"


- name: Compile Terminfo
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  ansible.builtin.command:
    cmd: tic -x /tmp/xterm-ghostty.src
    creates: "~/.terminfo/78/xterm-ghostty"
